---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/events
  label: Events
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - event
- type: heading
  label: Single texts
- type: document
  path: content/homeCopy.md
  label: Home Copy Text
- type: document
  path: content/homeAbout.md
  label: Home About Text
upload_dir: ban/img
public_path: https://res.cloudinary.com/architecturalnetworks/ban/img
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
